### ISSUE TITLE
option to disable frjump as admin

### ISSUE THREAD

**Issue by fdittz** [FortressOne/server-qwprogs#103]

**Comment by lordee** [comment]
rotate commands etc are already disabled

**Comment by lordee** [comment]
@fdittz are you seeing frjump working on your server?  In AU it's disabled (rotate command).  Not sure how much normal server admin stuff should be set from fortress admin menu (but i don't mind)

**Comment by fdittz** [comment]
it's still possible by tweaking pitchspeed values and such.
We usually disable them using serverinfo fpd:

`serverinfo fpd                206       // fpd values from qizmo.txt
                                        //   1 = disable %-reporting
                                        //   2 = disable use of powerup timer
                                        //   4 = disable use of soundtrigger
                                        //   8 = disable use of lag features
                                        //  16 = make qizmo report any changes in lag settins
                                        //  32 = silent %e enemy vicinity reporting (reporter doesn't see the message)
                                        //  64 = spectators can't talk to players and vice versa (voice)
                                        // 128 = silent %x and %y (reporter doesn't see the message)
                                        // 256 = disable skin forcing
                                        // 512 = disable color forcing`

In oztf however we can change fpd as admins, while currently in FO only with rcon password
