### ISSUE TITLE
Players get stuck when climbing ramps and hitting head on a platform

### ISSUE THREAD

**Issue by fdittz** [FortressOne/server-qwprogs#106]
Once climbing ramps and hitting head on any kind of ceiling it's not possible to move anymore, either strafing, moving forward or back, jumping or rjumping.

Happens only when running on FTESV, when running on Mvdsv it behaves normally
Video: https://streamable.com/9bcs4

**Comment by gmtandi** [comment]
sv_bigcoords 1
