### ISSUE TITLE
slots are little bit broken

### ISSUE THREAD

**Issue by drzel** [FortressOne/server-qwprogs#1063]
- ensure `fo_wpp_beta` is enabled
- bind x `+slot2`
- press `x`
- before weapon animation finishes, release, and press and hold
- watch as the wrong weapon fires

Game is basically unplayable if using slots for firing.

**Comment by drzel** [comment]
@newbytf change is good. Though it's still a bit broken with 2+ switches: https://www.youtube.com/watch?v=wWkIPM8dDIc

**Comment by newbytf** [comment]
I think this is working correctly given current slot aliases and the same as master.  

The problem with 2 buttons is that +attack does not stack so when you release the second +slot, its -attack clobbers.  The client has special handling for naked binds to +jump and +attack that behave differently from aliases.  To work correctly this would would need a +aux_attack which counted +attacks, the same as +aux_jump, then slots would need to use this.  You could also implement it in your config.
