### ISSUE TITLE
flag can be duplicated

### ISSUE THREAD

**Issue by lordee** [FortressOne/server-qwprogs#110]
Flag can be removed from player if they're against the wall at an angle.  This causes the flag to be "dropped". Teammates can pick up the flag, alternatively the original player can throw the flag which makes the duplicated one disappear.  If the original flag carrier does not throw the flag and a teammate picks up the flag, the original player no longer has the flag but still maintains a glow.

This would be fixed with FTE client change (show flag through csqc, don't have an actual flag ent following player serverside)

**Comment by drzel** [comment]
Woh cool - also agree not having an actual flag is ideal.

**Comment by mehtty** [comment]
In case this helps in the meantime, I had the same issue by:
1. Say a blue is carrying a red flag and stands on the blue one
2. A red player picks up the blue flag from under them
3. Blue flag shimmers betweent the two.
4. Sometimes other weird effects happen, like the flag model stays on the ground
This happens in bothe ftesv and mvdsv. Guess the flag picks the wrong touching person to attach itself to?
I like the csqc idea.
