### ISSUE TITLE
mvd link from stats link not working

### ISSUE THREAD

**Issue by RicksonFOLD** [FortressOne/server-qwprogs#1168]
On http://haze.fortressone.org/miami/staging/2023-07-26-00-55-32_[h5rdcore_b2]_blue_vs_red.html the MVD link leads to

<Error>
<script id="youtube-hd-fjdmkanbdloodhegphphhklnjfngoffa">var ythdlog = () => {};;var ythderror = () => {};</script>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>miami/staging/2023-07-26-00-55-32_[h5rdcore_b2]_blue_vs_red.mvd.gz</Key>
<RequestId>6N9S9S25Z6K1HTCZ</RequestId>
<HostId>5Gr1Wd9C2/a3WorzvU1rcR4nC13JyJ1dUPe1I7ud/i3Zspc1VefW3wLgP3LoIW8zhjXZ8160pVWF+IgP897ruQ==</HostId>
</Error>

**Comment by haze-au** [comment]
Miami not saving demos in .mvd.gz for some reason?
