### ISSUE TITLE
With 'FO_Autohop 1' Jump is frame late with Manual standing rocket jump

### ISSUE THREAD

**Issue by scaryguy334** [FortressOne/server-qwprogs#227]
Using autohop if you try to do a manual rocketjump with hit separate jump+attack keys together, eg 'mash at the same time', the jump appears to pop a frame+ late.
This results in rocket to the face and no jump.

This also happens with a script such as this budget get me up 2forts alias
+alias1 "cl_pitchspeed 100000;impulse 7;+lookdown;wait;-lookdown;cl_pitchspeed 150;+jump;+attack;"
-alias1 "-attack;-jump;force_centerview"
bind x +alias1

Note the lack of wait between +jump and +attack.
This works if you adjust the script with a wait between the two: 
"cl_pitchspeed 100000;impulse 7;+lookdown;wait;-lookdown;cl_pitchspeed 150;+jump;wait;+attack;"

**Comment by scaryguy334** [comment]
When using script version: 
- If standing over a ledge so you don't shoot any ground, jump will still happen so the jump isn't lost.

- Height achieved when shooting above ground is same as shooting rocket into floor.

- Jump sound still plays despite not getting any benefit of a jump.

**Comment by drzel** [comment]
Replicated this again today. Can consistently reproduce this around 1/4 RJs without using a script.
