### ISSUE TITLE
Soldier neutering

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#236]
The soldier is overdone. Overpowered, and overplayed. Everyone knows it. That's why he seems to enjoy over half the playtime of all 9 classes. Let's examine why this is. I see four primary reasons.

1) Rocket blasts. Which give three distinct advantages. It gives the ability to...
1a) go where others can't, horizontally and vertically, by rocket jumping.
1b) to rapidly accelerate, whether or not you are already moving quickly, for a relatively low damage cost.
1c) halt momentum of enemies traveling at super speeds.
2) Toughness. At 200/100 he's by far the toughest dude next to the hwguy.
3) Armament. He's deadly with 4 frag grenades, a shock grenade, rockets, double shotgun and shotgun he's arguably the second or third best killer in the game (sniper #1 and demo/sold competing).
4) He can quickly off himself without having saved grenades. His rockets are usually enough to quickly do him in at the end of his useful health/armor and grenade life.

Even before bunnyhopping came along, the soldier was a dominant class. Take his speed handicap away with the bunnyhop, and we are left with a superclass. I don't like it because one of the things I loved about Team Fortress was that you had to think about which classes to put where to be most effective on defense, and on offense had to consider which combination of classes would work best together to defeat a given defense.

I can see why people like to play him. Who wouldn't want to be a fast, priviledged-access, thwarting, tough, bad-ass motherfuckyouupper who can come back quickly to kick your ass again?
Now, let's talk about solutions. Probably not a good idea to affect #1 because people are too impatient, they want speed, rocket jumping is an important staple in the game and provides access to places hard to reach by others. Probably good to leave #4 because I like that he hurts himself when he uses rockets at close range and to rocket jump. I don't want to further empower the dude. So that leaves #2 and #3.

Possible solutions:
1) Take away frag grenades. Leave him with 1 or 2. Perhaps 1 frag, and 2 nail grenades?
2) Replace frag grenades with something less powerful. Perhaps smoke grenades that do some damage, akin to a flashbang? Hell, give him some flashbangs.
3) Reduce his armor. 100 life 110 armor -- about the same as a demoman.

**Comment by lordee** [comment]
we won't be nerfing soldier
