### ISSUE TITLE
No looking around after death

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#237]
Take away the ability to look around after death, to gather   intelligence like the location of the sentrygun that shot you in the back.   One step further would be to blacken the screen, so no data could be gathered   after death at all--or perhaps simply an instant respawn on quad mode.
--

**Comment by lowkeyau** [comment]
Hi Rickson,

Good suggestion, and your concern is acknowledged, however there's no move to be changing this. In saying that, there may be a move to change the respawn time as a possible trade off - but it won't be an instant spawn. 

Cheers
