### ISSUE TITLE
Reduce scout conc penalty

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#239]
Scout suggestion: Make the scout pay a 5-second penalty instead   of a 10-second penalty for conc's. Or, perhaps better, allow him to enjoy the   first conc without penalty. To make this intuitive, give him a helmet that   comes off or changes color upon being conc'd for the first time in his life   (and a little echo that says "You've lost your helmet. Prepare for   CTE."). Perhaps armor/engineer whack/dispenser would restore the helmet?
--

**Comment by drzel** [comment]
Please separate these into individual requests. Cuss time is already configurable.
