### ISSUE TITLE
Weaken the sniper

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#241]
Sniper suggestion: Rather than simply eliminating the most   feared, despised and respected character from the lineup, just reduce his   effectiveness to the point where he would be questionably effective--might be   used on some maps. The main thing would be to either reduce the power of the   sniper rifle, increase time to first fire or decrease the rate at which the   rifle powers up.
--

**Comment by drzel** [comment]
Sniper has been significantly weakened already.
