### ISSUE TITLE
Penalize the medic conc

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#243]
Medic suggestion: The medic is too dominant on offense. The   ability to conc great distances to reduce transit time, plus the ability to   conc in and out of an enemy flag area with the flag in tow is too powerful.   Either a penalty should be put in place (perhaps 5 seconds of conc effect?)   or the conc's should be limited to 1.
--

**Comment by drzel** [comment]
Medic cuss effect is being reviewed.
