### ISSUE TITLE
Ease up on the hwguy conc penalty

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#244]
Hwguy suggestion: The hwguy is currently too susceptible to   conc's. To remedy this, keep the same effect when his feet are off the ground   from the conc (no cannon ability), but when his feet are back on the ground,   limit the power of the cannon to, say, half (instead of the ~10% it currently   operates at while conc'd).
--

**Comment by drzel** [comment]
Agreed. This is also being reviewed.
