### ISSUE TITLE
Bring back burn damage

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#245]
Pyro suggestion: as in the days of old, allow the incendiary   cannon to do burn damage. I know it's really better to bring all the damage   at once, as it is now. However, I am suggesting to increase the damage done,   over time, such that it does more total damage than it currently does (or   probably ever did). This would make the pyro a prime candidate for front line   defense, or for wearing down an enemy defense. Pyros were attrition fighters   back in the day. One could burn a guy, go off and fight another guy, leave   him burning, then return to the first enemy to burn him some more. However,   if you, as a pyro, fight consistently with the same person, the burn damage   won't count for as much because the enemy will be continually burning, and   the multiple burns on top of each other won't do any more damage than one   would on it's own. In other words, an incendiary rocket might do 20 points of   damage over 20 seconds. If you hit an enemy with one rocket, then another one   20 seconds later, a total of 40 points of damage is scored. If you shoot an   enemy with 2 rockets 2 seconds apart, a total of 22 points of damage will be   scored.
--

**Comment by drzel** [comment]
We will do a a full pyro review in the future.
