### ISSUE TITLE
Allow burns to cause infection

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#246]
Pyro suggestion: make people with burn wounds more susceptible   to contracting an infection from their bio-infected teammates the water (they   may have used to quench their burning skin!) or even, perhaps the air and/or   walls?
--

**Comment by lowkeyau** [comment]
Hi Rickson,

This won't be implemented in the foreseeable future. Always happy to hear suggestions regarding the pyro though. 

Thanks
