### ISSUE TITLE
Allow disguise initiation while feigned

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#252]
Spy suggestion: as in the days of old, allow feigned spies to   initiate the changing of disguises. At the very least, allow the ability to   change into the last disguise. This ability is crucial with a sentrygun   looking at you, either while low on health or with human enemies present.
--

**Comment by lordee** [comment]
I thought this was working even on ezquake.. definitely a bug to be fixed
