### ISSUE TITLE
Allow feigned spies to jump

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#253]
Spy suggestion: as in the days of old, allow feigned spies to   jump!
--

**Comment by lowkeyau** [comment]
Hi Rickson,

Thanks for your suggestion. This will not be implemented, but can you elaborate on what purpose a jumping feigned spy would have? 

Cheers

**Comment by Rickson-FOLD** [comment]
Certainly.
1) If feigned spies were allowed to throw grenades, or if one unfeigned in the air, grens could be thrown a bit further.
2) If on a decline, one can skip down it utilizing the momentum from the vertical jump alone.
3) If there's a rocket or grenade coming at you, jumping, then unfeigning mid-air would allow the spy to gtfoutta there faster.
