### ISSUE TITLE
More cells in a dispenser

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#260]
Engineer suggestion: Have the dispenser store more than the 400   cells which is just enough for a L3 sentry gun. In today's game, few people   take any ammo from the dispenser, with notable exceptions being engineers   taking shells and cells, demomen taking rockets and the occasional hwguy   taking shells. The 400 shells, 600 nails, 300 rockets are a bit much! I   hereby declare the engineer is overdue to redesign his outdated dispenser.   Long-lived (well-placed, and not used for detonation) dispensers should be   able to reward the good engy with more utility. Or maybe by whacking it a few   times you can up the cell carrying capacity.
--

**Comment by lowkeyau** [comment]
Hi Rickson,

Thanks for your suggestion. Increasing the cells will not be considered right now as we think it's fairly balanced in aiding an engineer with building.

P.S, who doesn't love a dispenser death though?

Cheers
