### ISSUE TITLE
Dispensers display accurately

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#262]
Engineer suggestion: Make the dispenser graphs accurately   display what is inside the dispenser.
--

**Comment by lowkeyau** [comment]
Hi Rickson,

Another good suggestion. Right now it's not going to happen. The dev's have suggested various methods in which it could be done, but with no current assets team member as well as other dev priorities, this won't be looked at just yet.

Thanks
