### ISSUE TITLE
Psychedelic tolerance after capping while high

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#268]
Bug: gas grenades continue to give negative health consequences,   but no longer give psychedelic effects (even after inhaling some fresh gas)   after capturing the flag while hallucinating. I suppose this could also be   considered a feature: a rest-of-the-life bonus for capturing the flag.   Probably a bug that never needs to be addressed, but possibly a bug that   could point to other bugs.
--

**Comment by drzel** [comment]
We will be doing a full review of gas soon.
