### ISSUE TITLE
Feigned spies screw up elevators

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#269]
Spy bug: when on elevators, feigning causes elevators to   sometimes stop moving upwards. The feigned spy takes 1 point of damage as   this happens.
--

**Comment by lowkeyau** [comment]
Hi Rickson,

This has been tested and has not been replicated. This _may_ be due to lifts on some maps acting as doors and others as elevators. If you are able to replicate consistently, or have some more information on specific maps etc, please let us know or provide us with a demo. 

Thanks
