### ISSUE TITLE
Engineers should happily jump while building

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#270]
Engineer suggestion: as in the days of old, allow engineers to   jump (for joy? since they're so happy to be building?) while building (to avoid those pesky rockets and toss grens a bit further).
--

**Comment by lowkeyau** [comment]
Hi Rickson,

We have not yet decided whether this will be changed, and is something that may be considered for the future.

Cheers

**Comment by drzel** [comment]
Since drop sentries are the norm this is no longer relevant.
