### ISSUE TITLE
First scout conc unpenalized

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#273]
Scout suggestion: allow him to enjoy the first conc without   penalty. To make this intuitive, give him a helmet that comes off or changes   color upon being conc'd for the first time in his life (and a little echo   that says "You've lost your helmet. Prepare for CTE."). Perhaps   armor/engineer whack/dispenser would restore the helmet?
--

**Comment by lordee** [comment]
We have scout changes in pipeline, doubt we'll be doing this but will keep it in mind.
