### ISSUE TITLE
Have a +slott1

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#274]
Have a +slott1 that quick switches to the weapon, fires, then   leaves that weapon displayed. This way you can bind one reload key and be   able to reload your current weapon.
--

**Comment by lowkeyau** [comment]
Hi Rickson,

Thank you for your suggestion.

This is a feature that has been added to FTE and can be achieved through binds. Please let us know if this is a concurring issue. 

Cheers

**Comment by Rickson-FOLD** [comment]
Kindly, what is the command?
