### ISSUE TITLE
Eliminate, standardize bunnyhopping

### ISSUE THREAD

**Issue by Rickson-FOLD** [FortressOne/server-qwprogs#275]
I would classify this as both an enhancement and a bug. It's a   bug because bunnyhopping was never intended by the makers of Team Fortress.   Speed was an essential differentiator among the classes. However, it has now   become, sadly, a seeming inextricable part of the game. So to eliminate the   cumbersome task of learning to and executing the bunnyhop, I suggest a   progressively increasing speed simply be built into gameplay. It probably   shouldn't be as fast of an increase as advanced bunnyhoppers can do (sorry my   fellow dudes) but should be faster than bunnyhoppers getting the hang of it   could do. I think the maximum speeds for each class should be proportional to   their set speed. That annoying jump-jump-jump sound can then go away, too,   and begin to mean something again!
--

**Comment by lordee** [comment]
We have added autohop to help beginners, available in fte client
