### ISSUE TITLE
feature request: Movement preference settings server side?

### ISSUE THREAD

**Issue by scaryguy334** [FortressOne/server-qwprogs#335]
Do we want a way for people to setup their physics/movement preference so they can fire up their flavour of fortress?
eg:
No bhop mode (netquake)
q3 strafe jumps only
bhop but with speed caps

**Comment by scaryguy334** [comment]
q4 sliding bhop - from zut.

**Comment by drzel** [comment]
yep that works perfectly

**Comment by klownistrash** [comment]
did you try with a rj? i seem to be able to bh using a rocket.

**Comment by drzel** [comment]
yeah it's a graceful slow down

**Comment by drzel** [comment]
Also you cant turn - you can maintain with graceful slowdown in one direction only. It's exactly as I would have implemented it. Try on mbases to get a feeling for it.
