### ISSUE TITLE
reload complete message for message_trigger support

### ISSUE THREAD

**Issue by lordee** [FortressOne/server-qwprogs#39]

**Comment by drzel** [comment]
If a sound is wanted - maybe a sound should be played? Then the .wav can just be replaced if a custom sound is wanted.

**Comment by lordee** [comment]
Are you suggesting a stuffcmd instead?  Are messages of non-found sounds printed to console?  Also, would we want to force this?

Considering this is a new enhancement and maybe we want to edit this in the future, would it be better to have the string that people can manually msg_trigger now and we can support via menu selecting of sound/msg_trigger in FO in future release?

The idea of hardcoding (new) sounds is not so great to me... but that's mainly just complaints based.  But the idea of non-found sound issues are also a worry.

**Comment by drzel** [comment]
You’ve convinced me.
