### ISSUE TITLE
fte scoreboard

### ISSUE THREAD

**Issue by lordee** [FortressOne/server-qwprogs#470]
need to change damage to abbreviations when above 4 characters
don't count damage in prematch, or reset it
maybe some colours on some columns to help differentiate them

**Comment by mehtty** [comment]
Sometimes specs/observers seem to disappear
If possible, have AFK/msg indicators

**Comment by lordee** [comment]
Reset between rounds
Make a summary one for end of game too

**Comment by lordee** [comment]
allow specs to see all classes of both teams
caps on 32s reported as 2 for each one, same with another map - maybe all?

**Comment by lordee** [comment]
team kills not being tracked

**Comment by lordee** [comment]
sg damage not being counted

**Comment by lordee** [comment]
show who you are on scoreboard
show who you are speccing

**Comment by lordee** [comment]
when player comes in after caps occur, they aren't getting team score

**Comment by lordee** [comment]
specs can go missing when soemone drops maybe?
