### ISSUE TITLE
odd gameclock behaviour

### ISSUE THREAD

**Issue by drzel** [FortressOne/server-qwprogs#50]
with:

```
localinfo prematch 1
timelimit 10
```

Gameclock:
- shows 10:01 until countdown begins
- ticks down with countdown to 9:51
- shows 11:00 for one second
- shows 10:00 and starts counting down
- is 1 second out of sync with final countdown
- shows 10:00 for one second before match ends

The above is after reversing Viantriz's client changes (so default ezQuake).

**Comment by VianTORISU** [comment]
https://github.com/ezQuake/ezquake-source/commit/4dff33c7cef5da4fc6793cde594a4f4a893f88b3
or i'm missing something?
