### ISSUE TITLE
Reload inconsistency

### ISSUE THREAD

**Issue by scaryguy334** [FortressOne/server-qwprogs#502]
Reload will always reload to MAX clip size before giving you your gun back.
This is annoying to watch if you are staring at your bullets count up past your max left in bag.

Most noticeable as heavy cannon but also happens on any gun.

Eg have 120 shells
40 left in clip of cannon
Empty clip by firing and trigger reload
Watch the reload counter go all the way to 100 before snapping you back to 80 ammo.

Also....
Same situation above.
Empty clip by firing and trigger reload.
Pickup 20+ shells before reload is finished, so you actually now have the max clip size in inventory.
Watch it count to 100.
Once done have 80 in clip.
Sad heavy.

Fixing this could potentially buff every class and add reload tech (see people scripting) to get around having to wait for reloads just to get smaller clip back faster in a tight battle.

**Comment by Rickson-FOLD** [comment]
Great observation.
