### ISSUE TITLE
max movespeed not being met correctly - scout, hwguy

### ISSUE THREAD

**Issue by scaryguy334** [FortressOne/server-qwprogs#522]
Quake physics quirk prevents scout and hwguy from reaching their maxspeed due to not being a multiple of 4.
Max speeds are 450 and 230 respectively.

Instead you will see 448 and 228 if moving +forward or +moveright 
oddly +moveleft and +back will move correctly (at least for me!).

If you manually set cl_forwardspeed or cl_sidespeed to the next multiple of 4 above 450/230 or any value higher then the correct speed will be observed.
If you do not manually set cl_forwardspeed each time after spawn you will see the wrong speed for +forward.
oddly cl_sidespeed only needs to be set once.

**Work arounds**
Add an alias into your f_respawn alias trigger eg:
alias cl_movespeedfix "cl_forwardspeed 2000;cl_backspeed 2000;cl_sidespeed 2000"
alias f_respawn  "cl_movespeedfix"

If you are allergic to enabling f_triggers then alias your movement keys to include appropriate cl_xxxspeed values being set when you press a movekey.

Note: cl_xxxspeed value must be set by client each time you respawn as it is reset by the mod (I think?).

**Comment by drzel** [comment]
Interesting. I think we need to organise a race to confirm if it is real, or a reporting error.

**Comment by Rickson-FOLD** [comment]
Interesting. I noticed this but assumed it was a reporting error. Just in case, I put the following in my scout and hwguy configs, so every time I spawn it should give me a fraction of a percent faster speed advantage:

cl_forwardspeed 452
cl_sidespeed 452

cl_forwardspeed 232
cl_sidespeed 232
