### ISSUE TITLE
dropammo command only allows dropping of Shells first time

### ISSUE THREAD

**Issue by jhwee** [FortressOne/server-qwprogs#537]
With fteqw64.exe (5776), when I use the `dropammo` command, only Shells is enabled even though I have other types of ammo to drop. Only after I drop Shells am I allowed to drop the other types of ammo.

STR:
1. Use latest fteqw64.exe and fteplug_ezhud_x64.dll per fte-config repo.
2. Enter FortressOne server (I tested with California Trick, Virginia Clan and Sydney Staging)
3. Join any team, use any class (I tested with pyro, soldier and medic)
4. Open console, `bind x dropammo`
5. Press x, and see only Shells enabled even though you have sufficient ammo of other types.

**Comment by drzel** [comment]
@jhwee @mehtty is this one confirmed fixed?

**Comment by mehtty** [comment]
On staging only

**Comment by jhwee** [comment]
Yep, works for me! Thanks.
