### ISSUE TITLE
make dispenser use equal for both teams

### ISSUE THREAD

**Issue by scaryguy334** [FortressOne/server-qwprogs#542]
Dispenser withdrawal functionality is different for both teams. This should be made the same for both.

Friendlies get the clunky new method:
- Touch gives ammo, on a cooldown of X seconds (no idea what the cooldown is but it is TOO LONG imo)
- Press against slowly gives armor

Enemies get old method:
Brings up impulse menu to withdraw full ammo or armor every time on touch.

Opinion:
- old method is at advantage, can be done on the move to grab armor and go in one.
- New method needs a tweak on the cooldown of withdrawing ammo, or functionality change depending if you want to restore some strength to it.

**Comment by Rickson-FOLD** [comment]
Spot on.
