### ISSUE TITLE
engineer can no longer dismantle enemy buildings

### ISSUE THREAD

**Issue by lordee** [FortressOne/server-qwprogs#60]

**Comment by mehtty** [comment]
Not sure if same thing, but spannering an enemy sentry appears to stock it up with ammo, just before you are swiftly dispatched

**Comment by lordee** [comment]
Yeah, would prefer auto dismantle i think

**Comment by drzel** [comment]
Yeah he should be able to dismantle

Sent from my iPhone

On 13 Jun 2019, at 8:33 pm, Danni Uptlen <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah, would prefer auto dismantle i think
