### ISSUE TITLE
Joining (staging) server and being able to "Select Team" option disappearing. 

### ISSUE THREAD

**Issue by WolveriNE-AUNZ** [FortressOne/server-qwprogs#679]
Menu disappears if it is not actioned. User requires to have "changeteams" bound to join the game or reconnect. Typing 'join' in console only replies with 'join a team to ....'

**Comment by haze-au** [comment]
It seems that its due to connecting the server in some kind of observer / non-player state.

I have this issue when using 'connect <server>'.

Using 'join <server>' [in disconnected state] brings up the menu on connecting, using 'join' after connect throws error to reconnect.
