### ISSUE TITLE
Pub mode requires map rotation: Pub and Trick server

### ISSUE THREAD

**Issue by scaryguy334** [FortressOne/server-qwprogs#715]
Need to engage a map rotation either when server is set on pub mode or just applied against Pub / Trick servers. (maybe even duel server?)

Smaller maps like 2phase5r, poop, xpress, topaz, dkeep2, the mini well6 where middle is ramps room, mininmtrees, minitf2k, mini32s (i dont like mini32sr), mininoheros, 2machsep (or one of the 2mach variants).

Trick server might be harder since half of the maps require "serverinfo rj 2" to be set to actually complete. 
Should have a mix of non rj maps included as well. 
At the very least rj101, cj101 should be there (imo cj101 is actually quite hard). Povmed2 is broken as keys don't work as intended in the teleport to the end levels.
Some of the maps have hidden questionable textures so should be avoided.

**Comment by drzel** [comment]
Agreed. Though this is probably possible already with some config, not sure. See pubmode.cfg in the fortressonesv repo.
