### ISSUE TITLE
when you change weapon while assault cannon is spinning down, you can no longer shoot until you die

### ISSUE THREAD

**Issue by lordee** [FortressOne/server-qwprogs#72]

**Comment by lordee** [comment]
might also have an interaction with cuss, that's why i changed weapon

**Comment by lordee** [comment]
This is caused by running out of shells or cells and something causes you to stop firing (such as no shells...).  Game still has a flag set saying asscan is being fire.

**Comment by drzel** [comment]
Can't replicate that, tried, using all shells, changing weapon during cooldown, could always fire after restocking. Missing something?

**Comment by lordee** [comment]
Was discussed in discord, other suggestions:
When spinning down and you are in the air (so cussed or jump) and you try to spin up again during spin down, or change weapon during spin down, you can't attack?

Pure conjecture:
I think this is the asscan currently firing flag not being set to false (which is probably in one of the spin down functions?).  I think there are two, so assume flag is set at end of second one and we're skipping that through change of weapon/spin up?  I haven't tried to replicate, but noticing a complaint by "new" hw players.  I don't notice it as much anymore but I think I have modified my behaviour, whereas others that don't play it much just try to play normally...
