### ISSUE TITLE
Pkay sound on sentry death

### ISSUE THREAD

**Issue by drzel** [FortressOne/server-qwprogs#720]
From wolv:

msg_trigger sentrydet "Your sentry gun was destroyed"
alias sentrydet "say_team $$nick…eng: Nossa Sentry {DESTRUIDA!};say_team $$nick…eng: Nossa Sentry {DESTRUIDA!} ~misc/chink.wav"

Cabo from brasil has this in his config.
When I'm playing on his team and his sentry gun gets destroyed. It plays that wav file

**Comment by haze-au** [comment]
Interesting the MSG_TRIGGER no longer works in FTE but the teamplay ~xxx.wav sounds do.
