### ISSUE TITLE
Nerf / fix consecutive scout dashes without touching ground?

### ISSUE THREAD

**Issue by scaryguy334** [FortressOne/server-qwprogs#734]
Scout can currently spam dash off cooldown as many times as they wish assuming they haven't hit the ground

ie require some sort of 'on ground' to occur before next dash rather than an on cooldown which to me seems more intuitive. 

Opinion pros:
Add a bit of risk to getting bounced around rather than just lol spam dash your way through things.
Fix scout getting a free run to roof blitzkrieg2 without spending resource or time

**Comment by drzel** [comment]
Yep I agree.
