### ISSUE TITLE
Grabbing flags through lasers? - Phantom maybe others?

### ISSUE THREAD

**Issue by scaryguy334** [FortressOne/server-qwprogs#735]
Apparently possible to throw yourself at a laser and ignore trigger long enough to touch the flags in it's default position on phantom, which would also mean you could throw it out.

Don't have a direct clip of my POV doing this but below clip kicker jumps first ahead of me, then I do the same maneuver but actually get a touch on a flag in default position with laser up. 
See the chat log straight after kickers jump that shows me getting laser'd but also touching flag o.0
https://clips.twitch.tv/PiercingLitigiousShrewCoolStoryBob-t7nnz2aPZN2xTpoh

Not really sure what's going on here, maybe client can still touch stuff before it registers the laser occured?

**Comment by scaryguy334** [comment]
Slowing down clip frame by frame, flag touch happens and appears on kickers screen before laser death shows meaning server has reported to him a flag touch first and registered me hitting the trigger killing me second somehow.

**Comment by drzel** [comment]
Yeah the flag has a decent hit box. It used to go through walls as well so I agree it makes sense not to go through lasers either.
