### ISSUE TITLE
Engineer Build menu openable on all classes

### ISSUE THREAD

**Issue by scaryguy334** [FortressOne/server-qwprogs#762]
engineer FO csqc build menu is accessible and shows available options for all classes.
Ie go scout and you can open build menu, and even has dispenser available (due to number of cells a scout can hold).

Build menu should only be available when engineer (or access to valid weaponry cutf? )

**Comment by Granothon** [comment]
yeah this feels weird when I've forgot to switch configs for another class and build menu pops up
