### ISSUE TITLE
Long uptime server slowly becomes broken

### ISSUE THREAD

**Issue by scaryguy334** [FortressOne/server-qwprogs#803]
Servers with increased uptime become laggy.
Bandaid fix appears to be restarting every server in thst region.

Any idea why this might be?
Possible to manage this automatically or daily manual sweep by someone required.
Not everyone has rcon to fix it and not everyone joins a discord to report a bad experience.

**Comment by drzel** [comment]
Currently the servers' memory usage slowly ticks up over team, even when map is changed. Spoike did some work recently to significantly improve the situation but I haven't been able to update the FTESV version yet, I'll see if I can look into that later today. However from my testing the issue still isn't fully resolved, so yes, I think an automated restart of servers is required.

I think the most logical place to do this is the updater script. It is annoying when it runs when the server is in use anyway, so with a bit of work we can make it only run if the servers are empty, and perform a restart in the process.

**Comment by drzel** [comment]
I now expose the server start time in the serverinfo, so from here I ought to be able to query this with `qstat` and conditionally kill the server.
