### ISSUE TITLE
changing class during quadmode intermission sometimes doesn't work

### ISSUE THREAD

**Issue by drzel** [FortressOne/server-qwprogs#86]
see Twi sending `/demoman` message: https://www.twitch.tv/videos/387965354?t=00h10m22s

**Comment by lordee** [comment]
assume this is because just origins are changed rather than a "respawn"

**Comment by lordee** [comment]
looking at vid, there was no acknowledgement... so is this just packet loss? Need to test

**Comment by drzel** [comment]
So... I haven't worked out the parameters, but today during quad intermission, I spammed `hwguy` 20 times without response and it didn't work, however at other times it does work.

**Comment by lordee** [comment]
haven't seen this in a while - did fte upgrade fix it?

**Comment by drzel** [comment]
Happened to me in our last quad (I think).

**Comment by drzel** [comment]
That said, it's not a big deal, going to console and typing the name of the class is obsolete. Just spawn and `changeclass`.

**Comment by drzel** [comment]
hrmm, except in intermission.

**Comment by lordee** [comment]
Noticed an issue with this recently, did a change in intermission, then changed again and it said i was "already respawning as x class" and then respawned me as the first changed-to class.  Worth looking at to see if repeatable, might bring up/fix edge cases

**Comment by lordee** [comment]
I fixed this a while back..
