### ISSUE TITLE
Usability feedback and enhancement suggestions for new players

### ISSUE THREAD

**Issue by lordee** [FortressOne/server-qwprogs#89]
They really enjoyed the game overall. But didnt understand the full extent of class capabilities) i.e hw guy lock or detpack for demoman) ....game timer..map button count downs... binds for special uses for class

**Comment by lordee** [comment]
Reopening this as it needs discussion

**Comment by drzel** [comment]
I think the best solution for this is a series of how to videos that will serve as help and also marketing content.
