### ISSUE TITLE
Team selection

### ISSUE THREAD

**Issue by lordee** [FortressOne/server-qwprogs#92]
Can change to a team without there being a team spawn using impulses 101-104

**Comment by drzel** [comment]
I'm not sure what you mean here - could you elaborate a little?

**Comment by mehtty** [comment]
I've tried this - if you get into the game, join a team+class (get menus out of the way) and then manually enter impulse 101/102/103/104 you will forcefully change teams to blue/red/yellow/green respectively, even if the map doesn't support it (those impulses don't check). All the maps I've tried have spawned me at info_player_start for the missing teams.
