### ISSUE TITLE
build support for locs in to mod, use for flaginfo etc

### ISSUE THREAD

**Issue by lordee** [FortressOne/server-qwprogs#97]

**Comment by drzel** [comment]
does the mod need to support the locs? If we print the special chars (e.g. `%l` or whatever) to the client, won't it resolve these already if the loc is present?

**Comment by lordee** [comment]
This was discussed in discord.  The server side support is already in a PR.  Printing %l would not work as you would need to send the origin too.. and then you need to interpret it.  We could do this in csqc if we wanted, in which case it's basically the same code with the extra network traffic of sending the origin _constantly_ for flaginfo etc.

Preference would be to standardise loc reading on server side for simplicity's sake.  If we want to do csqc the only reason I could see for doing it is for custom locs (don't care about it) or if multiple language players play together (understandable!) however at the moment this is so rare (as in... never) that I wouldn't make it a priority.... If someone wants to do it then cool.

**Comment by drzel** [comment]
Cool makes sense.
