### ISSUE TITLE
build support for posting data to website to collect stats

### ISSUE THREAD

**Issue by lordee** [FortressOne/server-qwprogs#98]

**Comment by drzel** [comment]
I want to do this. Is there some documentation / code / chat logs you can point me to?

**Comment by drzel** [comment]
I want to do this. Is there some documentation / code / chat logs you can point me to?

**Comment by lordee** [comment]
Take a look at stats-tracking branch, it's 99% done there, just need to change the json to individual json deliveries and build the web end

**Comment by drzel** [comment]
Guess we'll call this done.
